### Hello Order

GET localhost:8060/


### Menu

GET localhost:8060/api/menu


### Menu filtered by Category Key

GET localhost:8060/api/menu/main-course/menu-items


### Menu filtered by Category Key Sorted By Price

GET localhost:8060/api/menu/main-course/menu-items?sort=price


### Menu filtered by unkown Category Key

GET localhost:8060/api/menu/-nothing-


### Post Valid Order

POST localhost:8060/api/order
Content-Type: application/json

{
  "cart": {
    "items": [
      {
        "itemId": "item-1",
        "itemTitle": "Spare Ribs",
        "count": 2,
        "itemPrice": 10.0,
        "total": 20.0
      }
    ]
  },
  "billingAddress": {
    "name": "Frank",
    "city": "Washington",
    "street": "Pennsylvania Avenue 1600",
    "zip": "12345"
  }
}


### Post Invalid Order

POST localhost:8060/api/order
Content-Type: application/json

{
  "cart": {
    "items": []
  },
  "billingAddress": {
  }
}
