GET localhost:8060/api/order

### Send Order

GET localhost:8060/api/order/send

### Menu

GET localhost:8060/api/menu


### Actuator Endpoints

http://localhost:8060/actuator

### Actuator Prometheus Registry

http://localhost:8060/actuator/prometheus

### Actuator Info

http://localhost:8060/actuator/info

### Actuator health

http://localhost:8060/actuator/health

### Actuator health liveness

http://localhost:8060/actuator/health/liveness

### Actuator health readiness

http://localhost:8060/actuator/health/readiness

### Send Order

GET localhost:8060/api/order/send