### Hello Order

GET localhost:8060/


### Post Invalid Order

POST localhost:8060/api/order
Content-Type: application/json

{
  "cart": {
    "items": []
  },
  "billingAddress": {
  }
}


### Menu

GET localhost:8060/api/menu


### Menu filtered by Category Key

GET localhost:8060/api/menu/sides/items


### Menu filtered by Category Key Sorted By Proce

GET localhost:8060/api/menu/main-course/items?sort=price


### Menu filtered by unkown Category Key

GET localhost:8060/api/menu/-nothing-


### Menu with Response Entity

GET localhost:8060/api/menu/response-entity


### API Docs

GET http://localhost:8060/v3/api-docs.yaml


### Order Crash with Exception

GET localhost:8060/api/order/crash


### Order to Kitchen

GET localhost:8060/api/order-to-kitchen
