name: freddy-bbq

services:

  shop-frontend:
    container_name: shop-frontend
    build: shop-frontend
    environment:
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=shop-frontend
      - OTEL_TRACES_SAMPLER=always_on
    ports:
      - "4200:4200"

  order:
    container_name: order
    build: order
    environment:
      - DELIVERY_SERVICE_URL=http://delivery:8050
      - KITCHEN_SERVICE_URL=http://kitchen:8070
      - OTEL_HOST=otel-collector
    ports:
      - "8060:8060"

  delivery:
    container_name: delivery
    build: delivery
    environment:
      - OTEL_HOST=otel-collector
    ports:
      - "8050:8050"

  kitchen:
    container_name: kitchen
    build: kitchen
    environment:
      - OTEL_HOST=otel-collector
    ports:
      - "8070:8070"

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    command:
      - --config=/etc/otelcol-contrib/otel-collector.yml
    volumes:
      - ./docker/collector/otel-collector.yml:/etc/otelcol-contrib/otel-collector.yml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one

  # Jaeger
  jaeger-all-in-one:
    container_name: jaeger-all-in-one
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
