server:
  port: 8060

spring:
  application:
    name: order
management:
  otlp:
    # Tracing 1
    tracing:
      endpoint: http://${OTEL_HOST:localhost}:4318/v1/traces
    metrics:
      export:
        enabled: false
  # Tracing 2
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: health

kitchen-service:
  url: http://localhost:8070

delivery-service:
  url: http://localhost:8060
