spring:
  application:
    name: delivery
  jackson:
    serialization:
      write-dates-as-timestamps: false
management:
  otlp:
    tracing:
      endpoint: http://${OTEL_HOST:localhost}:4318/v1/traces
    metrics:
      export:
        enabled: false
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: health
#  metrics:
#    tags:
#      service: kitchen

server:
  port: 8050

kitchen-service:
  url: http://localhost:8070